name: Test
on:
  push:
    branches:
      - master
  create:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest]    
        os: [ubuntu-latest] 
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}